### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by treeowl**
- Remove unnecessary constraints from `Data.BitSet.Generic`
- Use a more streamlined implementation of `foldl'` and `foldr'`
  when possible.
- Update Cabal file to indicate required extensions.
- Make the tests work again.

### CODE REVIEW

**Comment by superbobry** [comment]
This looks very good! Could you amend/push it once again to make Travis build the PR?

**Comment by treeowl** [comment]
@superbobry, I used the latest multi-GHC Travis config with the defaults. It's possible that some changes are needed to get the configuration you wanted. The old thing looked pretty old.

**Comment by treeowl** [comment]
Hmmm... It looks like there's an issue open regarding recent GHC; I'll probably have to re-restrict the version bounds, but I want to see how the tests fall first.

**Comment by treeowl** [comment]
I went too far trying to update `.travis.yml`. I've reverted that bit. I *think* everything else is sane. The Travis stuff will have to wait for a later PR. There are some majorly unpleasant problems relating to https://github.com/bos/aeson/pull/426, it seems.

**Comment by treeowl** [comment]
@superbobry, it appears that the remaining test failures are caused by bit rot and are not my fault. I believe this should be ready to merge if you like it.

**Comment by treeowl** [comment]
Hrmm... Need to improve one test, actually.

**Comment by treeowl** [comment]
Yeah, that should do it.

**Comment by treeowl** [comment]
@superbobry, once this is merged, I have a nice juicy bag of list fusion stuff for you.

**Comment by superbobry** [comment]
Thank you very much!

**Comment by treeowl** [comment]
And thank you! I may come up with a solution that covers the signed case
nicely as well, but right now I'm bashing my head against
Data.Sequence.fromList with Lennart Spitzner, trying to get more of the
intermediate representation into the call stack.

**Pull request merged**
